## Упражнения по библиотеке Numpy

In [157]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [158]:
arr = np.random.randint(0, 10, size=10)
print("Исходный массив:", arr)

bool_mask = (arr > 3) & (arr < 8)
arr[bool_mask] = -arr[bool_mask]

print("Измененный массив:", arr)

Исходный массив: [4 2 6 2 2 3 8 9 8 8]
Измененный массив: [-4  2 -6  2  2  3  8  9  8  8]


**2.** Заменить максимальный элемент случайного массива на 0

In [159]:
arr = np.random.randint(1, 100, 10)
print("Исходный массив:", arr)

max_index = np.argmax(arr)
arr[max_index] = 0
print("После замены:   ", arr)

Исходный массив: [ 5 40 21 12 84 22 78 91 55 70]
После замены:    [ 5 40 21 12 84 22 78  0 55 70]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [160]:
arr_in = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print("Входные массивы (строки):")
print(arr_in)
#???
grid = np.meshgrid(*arr_in)
stacked = np.stack(grid, axis=-1)
res = stacked.reshape(-1, len(arr_in))

print("Прямое произведение:")
print(res)

Входные массивы (строки):
[[1 2]
 [3 4]
 [5 6]]
Прямое произведение:
[[1 3 5]
 [1 3 6]
 [2 3 5]
 [2 3 6]
 [1 4 5]
 [1 4 6]
 [2 4 5]
 [2 4 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [161]:
a = np.random.randint(0, 10, (8, 3))
b = np.random.randint(0, 10, (2, 2))

print("Массив A:")
print(a)
print("Массив B:")
print(b)

check1 = np.isin(a, b[0]).any(axis=1)
check2 = np.isin(a, b[1]).any(axis=1)

mask = check1 & check2
result = a[mask]

print("Найденные строки в A:")
print(result)

Массив A:
[[3 6 4]
 [2 4 8]
 [8 3 9]
 [1 6 7]
 [0 4 1]
 [1 1 9]
 [1 0 9]
 [0 6 3]]
Массив B:
[[2 5]
 [5 3]]
Найденные строки в A:
[]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [162]:
mat = np.random.randint(0, 3, (10, 3))
mat[1] = [1, 1, 1]
mat[5] = [2, 2, 2]

print("Исходная матрица:")
print(mat)

all_equal_mask = (mat == mat[:, 0:1]).all(axis=1)

not_equal_mask = ~all_equal_mask
result = mat[not_equal_mask]

print("Строки, где не все элементы равны:")
print(result)

Исходная матрица:
[[2 1 0]
 [1 1 1]
 [1 1 2]
 [1 2 2]
 [2 0 2]
 [2 2 2]
 [1 1 0]
 [0 2 1]
 [0 2 1]
 [0 0 0]]
Строки, где не все элементы равны:
[[2 1 0]
 [1 1 2]
 [1 2 2]
 [2 0 2]
 [1 1 0]
 [0 2 1]
 [0 2 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [163]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])

print("Исходный массив:")
print(mat)

result = np.unique(mat, axis=0)

print("Массив без дубликатов строк:")
print(result)

Исходный массив:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]
Массив без дубликатов строк:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [164]:
def diagonal_product_no_numpy(matrix):
    diagonal = [matrix[i][i] for i in range(min(len(matrix), len(matrix[0])))]
    
    product = 1
    for element in diagonal:
        if element != 0:
            product *= element
    
    return product

def diagonal_product_numpy(matrix):
    return np.prod(np.diag(matrix)[np.diag(matrix) != 0])

X_list = [[1, 0, 1],
          [2, 0, 2],
          [3, 0, 3], 
          [4, 4, 4]]

X_numpy = np.array([[1, 0, 1],
                    [2, 0, 2],
                    [3, 0, 3],
                    [4, 4, 4]])

print("=== Задача 1: Произведение ненулевых элементов на диагонали ===")
print(f"Матрица: {X_list}")
print(f"Без NumPy: {diagonal_product_no_numpy(X_list)}")  
print(f"С NumPy: {diagonal_product_numpy(X_numpy)}")      

=== Задача 1: Произведение ненулевых элементов на диагонали ===
Матрица: [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
Без NumPy: 3
С NumPy: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [165]:
def task2_list(x, y):
    return sorted(x) == sorted(y)

def task2_numpy(x, y):
    return np.array_equal(np.sort(x), np.sort(y))

x_list = [1, 2, 2, 4]
y_list = [4, 2, 1, 2]
x_np = np.array(x_list)
y_np = np.array(y_list)

print(f"x = {x_list}, y = {y_list}")
print("List:", task2_list(x_list, y_list))
print("Numpy:", task2_numpy(x_np, y_np))

x = [1, 2, 2, 4], y = [4, 2, 1, 2]
List: True
Numpy: True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [166]:
def task3_list(x):
    vals = []
    for i in range(len(x) - 1):
        if x[i] == 0:
            vals.append(x[i+1])

    return max(vals) if vals else None

def task3_numpy(x):
    zero_mask = (x == 0)

    vals = x[1:][zero_mask[:-1]]

    return vals.max() if vals.size > 0 else None

x_list = [6, 2, 0, 3, 0, 0, 5, 7, 0]
x_np = np.array(x_list)

print(f"x = {x_list}")
print("List:", task3_list(x_list))
print("Numpy:", task3_numpy(x_np))

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
List: 5
Numpy: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [167]:
def task4_list(x):
    if not x:
        return ([], [])

    vals = []
    counts = []

    curr_val = x[0]
    curr_count = 1

    for i in range(1, len(x)):
        if x[i] == curr_val:
            curr_count += 1
        else:
            vals.append(curr_val)
            counts.append(curr_count)
            curr_val = x[i]
            curr_count = 1

    vals.append(curr_val)
    counts.append(curr_count)

    return (vals, counts)

def task4_numpy(x):
    if x.size == 0:
        return (np.array([]), np.array([]))

    diff_mask = np.diff(x)
    change_indices = np.where(diff_mask != 0)[0]

    run_starts = np.concatenate(([0], change_indices + 1))

    vals = x[run_starts]

    run_ends = np.concatenate((change_indices + 1, [len(x)]))
    counts = run_ends - run_starts

    return (vals, counts)

x_list = [2, 2, 2, 3, 3, 3, 5, 5]
x_np = np.array(x_list)

print(f"x = {x_list}")
print("List:", task4_list(x_list))
print("Numpy:", task4_numpy(x_np))

x = [2, 2, 2, 3, 3, 3, 5, 5]
List: ([2, 3, 5], [3, 3, 2])
Numpy: (array([2, 3, 5]), array([3, 3, 2]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
import time
from scipy.spatial.distance import cdist

def task5_list(X, Y):
    dist_matrix = []
    for row_x in X:
        row_dists = []
        for row_y in Y:
            sum_sq = 0
            for k in range(len(row_x)):
                sum_sq += (row_x[k] - row_y[k])**2
            row_dists.append(sum_sq**0.5)
        dist_matrix.append(row_dists)
    return np.array(dist_matrix)

def task5_numpy(X, Y):
#???
    x_broad = X[:, np.newaxis, :]
    y_broad = Y[np.newaxis, :, :]

    diff = x_broad - y_broad
    dist_sq = np.sum(diff**2, axis=2)

    return np.sqrt(dist_sq)

M = 100
N = 80
K = 10

X_np = np.random.rand(M, K)
Y_np = np.random.rand(N, K)
X_list = X_np.tolist()
Y_list = Y_np.tolist()

start_list = time.time()
dist_list = task5_list(X_list, Y_list)
end_list = time.time()
print(f"List (Python) time: {end_list - start_list:.6f} s")

start_np = time.time()
dist_np = task5_numpy(X_np, Y_np)
end_np = time.time()
print(f"Numpy time:         {end_np - start_np:.6f} s")

start_scipy = time.time()
dist_scipy = cdist(X_np, Y_np, 'euclidean')
end_scipy = time.time()
print(f"Scipy cdist time:   {end_scipy - start_scipy:.6f} s")

print("\nNumpy vs Scipy (проверка):", np.allclose(dist_np, dist_scipy))
print("List vs Scipy (проверка):", np.allclose(dist_list, dist_scipy))

List (Python) time: 0.045995 s
Numpy time:         0.002412 s
Scipy cdist time:   0.000508 s

Numpy vs Scipy (проверка): True
List vs Scipy (проверка): True


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [169]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [170]:
calorie_stats = np.loadtxt("cereal.csv", delimiter=",")

print(calorie_stats)
print(f"Загружено {len(calorie_stats)} записей.")

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]
Загружено 77 записей.


2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [171]:
average_calories = np.mean(calorie_stats)

print(f"Средняя калорийность конкурентов: {average_calories}")
print(f"Разница с CrunchieMunchies: {average_calories - 60}")

Средняя калорийность конкурентов: 106.88311688311688
Разница с CrunchieMunchies: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [172]:
calorie_stats_sorted = np.sort(calorie_stats)

print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [173]:
median_calories = np.median(calorie_stats)

print(f"Медианная калорийность: {median_calories}")
print(f"Средняя калорийность была: {average_calories}")

Медианная калорийность: 110.0
Средняя калорийность была: 106.88311688311688


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [174]:
nth_percentile = 0

for i in range(1, 101):
    p_val = np.percentile(calorie_stats_sorted, i)

    if p_val > 60:
        nth_percentile = i
        print(f"Найден {i}-й процентиль. Его значение: {p_val}")
        print("Это наименьший процентиль, превышающий 60 калорий.")
        break

Найден 4-й процентиль. Его значение: 70.0
Это наименьший процентиль, превышающий 60 калорий.


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [175]:
more_calories_mask = calorie_stats > 60

more_calories = np.mean(more_calories_mask) * 100

print(f"{more_calories:.2f}% хлопьев имеют > 60 калорий.")

96.10% хлопьев имеют > 60 калорий.


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [176]:
calorie_std = np.std(calorie_stats)

print(f"Стандартное отклонение: {calorie_std:.2f}")

print("\nКак это использовать:")
print("Высокое отклонение показывает, что калорийность сильно 'скачет' от бренда к бренду.")
print("Но, как мы уже видели, почти 96% из них все равно калорийнее наших 60.")
print("Это значит, что CrunchieMunchies - не просто 'чуть-чуть' лучше, а находятся")
print("в самой низкой и здоровой категории на рынке.")

Стандартное отклонение: 19.36

Как это использовать:
Высокое отклонение показывает, что калорийность сильно 'скачет' от бренда к бренду.
Но, как мы уже видели, почти 96% из них все равно калорийнее наших 60.
Это значит, что CrunchieMunchies - не просто 'чуть-чуть' лучше, а находятся
в самой низкой и здоровой категории на рынке.


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [177]:
summary = f"""
CrunchieMunchies (60 калорий) являются одним из самых здоровых вариантов.

Средняя калорийность конкурентов ({average_calories:.0f}) и медианная ({median_calories:.0f})
почти вдвое выше нашей.

{more_calories:.0f}% всех хлопьев на рынке калорийнее,
чем CrunchieMunchies. Наш продукт находится в {nth_percentile}-м процентиле.
"""

print(summary)


CrunchieMunchies (60 калорий) являются одним из самых здоровых вариантов.

Средняя калорийность конкурентов (107) и медианная (110)
почти вдвое выше нашей.

96% всех хлопьев на рынке калорийнее,
чем CrunchieMunchies. Наш продукт находится в 4-м процентиле.

